### ISSUE TITLE
All binaries in nuget are 64-bit. Any plans to add 32-bit binaries?

### ISSUE THREAD

**Issue by santolex** [ForNeVeR/tdlib.native#12]

**Comment by ForNeVeR** [comment]
Hello!

I am currently satisfied with 64-bit binaries for all platforms, so I have no personal plans to add 32-bit builds to the project. But if you wanna help, I'd gladly accept such a contribution.

If you know how to build 32-bit binaries on 64-bit Ubuntu we'ru currently using, please post them here or fork the project and try yourself to build them on Appveyor.
