### ISSUE TITLE
TDLib v1.4.0

### ISSUE THREAD

**Issue by Bannerets** [ForNeVeR/tdlib.native#13]
Hello, could you update binaries to tdlib 1.4.0?

**Comment by ForNeVeR** [comment]
Yes, will do in the meantime, thanks for the reminder!

**Comment by ForNeVeR** [comment]
I've decided we'll skip publication of 1.4.0 release since we have no tests for it. We'll proceed with publishing 1.5 (#23) and then 1.6 (#25).
