### ISSUE TITLE
I cant install tdlib.native for .net 4.7.2

### ISSUE THREAD

**Issue by eordukaya** [ForNeVeR/tdlib.native#14]
I develop asp.net mvc project via c# in .net 4.7.2 freamwork. I cant install tdlib.native for this project.
 
![Ekran Alıntısı](https://user-images.githubusercontent.com/34960896/58031312-d0975e00-7b28-11e9-94da-88cb07245fd4.PNG)

**Comment by ForNeVeR** [comment]
The package layout is targeted at the "new" .NET SDK. Please update to the new SDK. Just checked, and the project could be installed then. For example, with this csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="tdlib.native" Version="1.3.0" />
  </ItemGroup>

</Project>
```

**Comment by eordukaya** [comment]
thanks but where can I edit. I cant find there.

![Ekran Alıntısı](https://user-images.githubusercontent.com/34960896/58036674-5a98f400-7b34-11e9-8a38-7c4f24b1c65b.PNG)

**Comment by eordukaya** [comment]
this is file presentation. which file do I have to edit.

![Ekran Alıntısı](https://user-images.githubusercontent.com/34960896/58036801-9fbd2600-7b34-11e9-98a7-98a85dfb1efc.PNG)

**Comment by ForNeVeR** [comment]
Usually you edit the project file (in Visual Studio, I presume?) by right-clicking it and pressing "Edit project file" or something like that. For old project files, you'll need to unload the project first.

But I'm very skeptical about Visual Studio tooling in regard to (old?) ASP.NET projects with .NET SDK.

Please consider upgrading to ASP.NET Core, everything will suddenly become easier.
