### ISSUE TITLE
TDLib v1.5.0

### ISSUE THREAD

**Issue by Bannerets** [ForNeVeR/tdlib.native#23]
https://github.com/tdlib/td/releases/tag/v1.5.0
https://github.com/tdlib/td/blob/435d8b4/CHANGELOG.md

**Comment by uoziod** [comment]
🙏

**Comment by x2bool** [comment]
@ForNeVeR What do you think about GitHub Actions? I wonder whether we could port the build instructions to use GitHub Actions? In that way we could support the TDLib.Native project with the help of community.

**Comment by ForNeVeR** [comment]
@x2bool

Yep, we coud port the build instructions. Honestly, I can't see any immediate benefit of in doing that, but I believe that'd be a good idea in the long run. Here's a task for it: #24.

Please note that currently it's not the CI that's blocking us from upgrading to tdlib 1.5.0; we're blocked on #16 which itself is blocked by macOS test failures in tdsharp you've reported to me. I will work on them pretty soon (you can expect fix before 2020-01-09).

**Comment by ForNeVeR** [comment]
Since 1.5 has a [known bug](https://github.com/tdlib/td/issues/863) which breaks all of our unit tests, we won't be publishing it. We'll proceed with 1.6, see #25.
