### ISSUE TITLE
Add x64 Linux build

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/tdlib.native#3]

**Comment by mortezae** [comment]
Hi. I don't know if your Linux release is 32 or 64 but it exits with error code 139 (I call it via nodegin/tglib library) on my Ubuntu18.04 64bit
BTW the one form [Bannerets](https://github.com/Bannerets/tdlib-binaries/tree/master/1.2.0/linux64) works for me without problems.

**Comment by ForNeVeR** [comment]
Yas, I very much consider my linux binaries 64 bit:

```console
$  objdump -f ./libtdjson.so | grep ^architecture
architecture: i386:x86-64, flags 0x00000150:
```

It looks like you have some other issue with the binary. Could you please help me to diagnose it?

**Comment by mortezae** [comment]
@ForNeVeR Yes of course! just tell me what to do.
And thanks for objdump

**Comment by ForNeVeR** [comment]
Could you please share the code you run to reproduce the issue? I'll check it in my environment with my build of tdlib.

For now, we have some complaints from Debian users, but I still haven't enough time to research the situation. I was checking the binary on my Linux VM (it was Ubuntu 18.04 x64 I think), but the check procedure was convoluted enough, so I could easily miss something.

**Comment by mortezae** [comment]
I don't run any special code. Even a basic auth doesn't work:
`const { Client } = require('tglib')

void async function() {
  const client = new Client({
    apiId: '269276',
    apiHash: 'abcdefg2d7054557f8f8f80e7d3ea66e',
    auth: {
      type: 'user',
      value: '+98123456789',
    },
  })
  await client.ready
)}
`

**Comment by Bannerets** [comment]
I tested that binary with your code on Ubuntu 18.04 inside docker, it works for me.
https://github.com/Bannerets/tdlib-binaries/tree/master/1.2.0/linux64 is for different tdlib version (1.2.0), this may be the reason why it works.

Maybe try to increase verbosity level?

```js
// ...
  const client = new Client({
    apiId: '269276',
    apiHash: 'abcdefg2d7054557f8f8f80e7d3ea66e',
    auth: {
      type: 'user',
      value: '+98123456789',
    },
    verbosityLevel: 5 // <--
  })
// ...
```

If you use `tglib` wrapper, logs should be somewhere in `__tglib__/.../logs.txt` file.

**Comment by mortezae** [comment]
Hi @Bannerets , I'm aware about version difference but I thought it may be caused by some incompatibility with my system. 
This is the log with high verbosity:
```
[ 3][t 4][1549531708.382018805][Td.cpp:4238][!Td][&td_requests]	Sending update: updateAuthorizationState {
  authorization_state = authorizationStateWaitTdlibParameters {
  }
}

[ 3][t 4][1549531708.448084831][Td.cpp:3308][!Td][&td_requests]	Receive request 1: setTdlibParameters {
  parameters = tdlibParameters {
    use_test_dc = false
    database_directory = "/home/morteza/td/__tglib__/1123450312/database"
    files_directory = "/home/morteza/td/__tglib__/1123450312/files"
    use_file_database = false
    use_chat_info_database = false
    use_message_database = true
    use_secret_chats = true
    api_id = 269276
    api_hash = "a370bba2d7054557c75eaf0e7d3ea66e"
    system_language_code = "en"
    device_model = "tglib"
    system_version = "2.1.1"
    application_version = "1.0"
    enable_storage_optimizer = true
    ignore_file_names = false
  }
}

[ 3][t 4][1549531708.658349752][Binlog.cpp:368][!Td]	Load: init encryption
[ 3][t 4][1549531708.696191549][Td.cpp:4238][!Td][&td_requests]	Sending update: updateAuthorizationState {
  authorization_state = authorizationStateWaitEncryptionKey {
    is_encrypted = true
  }
}

[ 3][t 4][1549531708.696281910][Td.cpp:4253][!Td][&td_requests]	Sending result for request 1: ok {
}

[ 3][t 4][1549531708.710051537][Td.cpp:3308][!Td][&td_requests]	Receive request 2: checkDatabaseEncryptionKey {
  encryption_key = bytes [0] { }
}

[ 3][t 4][1549531708.710254669][Binlog.cpp:368][!Td]	Load: init encryption

```

**Comment by mortezae** [comment]
Hi @Bannerets , I'm aware about version difference but I thought it may be caused by some incompatibility with my system.
This is the log with high verbosity:

```
[ 3][t 4][1549531708.382018805][Td.cpp:4238][!Td][&td_requests]	Sending update: updateAuthorizationState {
  authorization_state = authorizationStateWaitTdlibParameters {
  }
}

[ 3][t 4][1549531708.448084831][Td.cpp:3308][!Td][&td_requests]	Receive request 1: setTdlibParameters {
  parameters = tdlibParameters {
    use_test_dc = false
    database_directory = "/home/morteza/td/__tglib__/1123450312/database"
    files_directory = "/home/morteza/td/__tglib__/1123450312/files"
    use_file_database = false
    use_chat_info_database = false
    use_message_database = true
    use_secret_chats = true
    api_id = 269276
    api_hash = "abcdba2d7054557c75eaf0e7d3ea66e"
    system_language_code = "en"
    device_model = "tglib"
    system_version = "2.1.1"
    application_version = "1.0"
    enable_storage_optimizer = true
    ignore_file_names = false
  }
}

[ 3][t 4][1549531708.658349752][Binlog.cpp:368][!Td]	Load: init encryption
[ 3][t 4][1549531708.696191549][Td.cpp:4238][!Td][&td_requests]	Sending update: updateAuthorizationState {
  authorization_state = authorizationStateWaitEncryptionKey {
    is_encrypted = true
  }
}

[ 3][t 4][1549531708.696281910][Td.cpp:4253][!Td][&td_requests]	Sending result for request 1: ok {
}

[ 3][t 4][1549531708.710051537][Td.cpp:3308][!Td][&td_requests]	Receive request 2: checkDatabaseEncryptionKey {
  encryption_key = bytes [0] { }
}

[ 3][t 4][1549531708.710254669][Binlog.cpp:368][!Td]	Load: init encryption
```

**Comment by Bannerets** [comment]
OpenSSL version incompatibility causes this. See https://github.com/tdlib/td/issues/259#issuecomment-397348244 and https://github.com/Bannerets/tdl/issues/7#issuecomment-397334932.

**Comment by mortezae** [comment]
So to work with this binary I should test some downgrades in nvm node version...
Thank you for your detailed help @Bannerets . I'll be watchful if ForNeVeR wanted brought us a new compiled binary :)

**Comment by mortezae** [comment]
I tested Node 8.9.4 . It is compiled against openssl 1.0.2n and it works properly with this binary. Not sure about 9.x versions.

**Comment by ForNeVeR** [comment]
One possible idea is to link static openssl.

**Comment by mortezae** [comment]
Hello there
Toady at the morning I had an unsuccessful login attempt(cuz of 2 step login proccess). I had installed binaries from more than one repository so not sure about the source of this security threat. Here I just wanted to warn people about running recompiled binaries by third parties. Always run them by your responsibility.

**Comment by ForNeVeR** [comment]
Yes, that's a right idea anyways.

In defense of my repository, I could only mention that all the sources and the build infrastructure are open source, and I build official tdlib sources cloned from the official repo. Everyone are welcome to reproduce my binaries using the same sources and scripts (unless Appveyor build infrastructure or tdlib sources themselves got compormised, the resulting binaries should be more or less identical).

**Comment by mortezae** [comment]
@ForNeVeR I have already tried Appveyor but didn't manage to compile. It seems that it doesn't have the build dependency 'gperf' installed. Could you please help me to compile it myself?

**Comment by ForNeVeR** [comment]
x64 Linux build has been added, for any additional problems please open new issues, and I am willing to accept any help in maintaining these.

**Comment by mortezae** [comment]
> Hello there Toady at the morning someone had an unsuccessful login attempt into my telegram account (cuz of 2 step login process). I had installed binaries from more than one repository so not sure about the source of this security threat. Here I just wanted to warn people about running compiled binaries by third parties. Always run them by your own responsibility.

I accidentally remembered of this old issue. Here I just wanted to mention: After this time, I had another similar observation (about a year ago). Finally turned out it was some unsuccessful spying activity from the state guys (IR). I'm not a so called activist or something. Their behavior regarding regular citizens is offensive and malicious.
Sorry for possible annoying, if any. @Bannerets @ForNever

**Comment by ForNeVeR** [comment]
@mortezae,

First of all, this is a strange place to report that.

Second: if you suspect the binaries from tdlib.native are compromise, then… well, technically that's possible. I am working to establish a very transparent process of building and uploading them (where everything is automated, built and tested on clean images and then published, so that anyone may check that the binaries weren't tampered with at any stage), but we aren't there yet, and we were even farther from there in 2019.

And yet, _to the best of my knowledge_, all the builds were fully automated even then (though some manual intervention was required and is still required for me to upload the resulting binaries, so there's that), and nobody approached me in these years about anything about these binaries being compromised.

_As of now_, I see no reason to consider tdlib.native's build process to have a security breach of any kind, at any moment in the past even.

If anything changes and I'm made aware of any such problems, I'll make sure to publish this information in a responsible way (as quickly as possible, while considering the safety of existing users).

Again, at the present day, there were no security incidents (or anything alike) reported to me. So, it is very possible that you were supposedly hacked via some other ways.

Lastly, if somebody was able to tamper with the binaries, wouldn't they be able to upload your cloud password to their servers? I'm not sure protocol allows that, but most likely, if someone owns the binaries, then they could make sure to do a _successful_ attempt to breach into your account. While you have only reported an _unsuccessful_ one.
