### ISSUE TITLE
Support for .NET Framework?

### ISSUE THREAD

**Issue by Trumeet** [ForNeVeR/tdlib.native#31]
Hi, I'm trying to add this package to a .NET Framework 4.8 project and encountered the following error: 
`Could not install package 'tdlib.native 1.6.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.	`

Does this library support .NET Framework? If not, are there any plan or alternative methods to use this library in .NET Framework? Thanks.

**Comment by ForNeVeR** [comment]
Could you please share your csproj file?

**Comment by ForNeVeR** [comment]
This issue looks similar to #30, but I had no answer from the issue author, and weren't able to reproduce the issue myself.

**Comment by Trumeet** [comment]
> Could you please share your csproj file?

Sorry I had already switched to the official TdLib, but the following gist would be still helpful:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>...</ProjectGuid>
    <OutputType>Exe</OutputType>
    <RootNamespace>...</RootNamespace>
    <AssemblyName>...</AssemblyName>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Deterministic>true</Deterministic>
    <TargetFrameworkProfile />
  </PropertyGroup>
```

**Comment by ForNeVeR** [comment]
This is, indeed, a project based on the old SDK. Please use a project with new SDK (aka ".NET Core SDK"), and you'll be able to install the package.

Please note that .NET Core SDK still supports building the apps for .NET Framework.
