### ISSUE TITLE
It would be possible to include the build for arm-linux and make it compatible with Raspberry Pi?

### ISSUE THREAD

**Issue by dieletro** [ForNeVeR/tdlib.native#32]
Maybe that helps: https://github.com/tdlib/td/issues/49

**Comment by ForNeVeR** [comment]
Hi! I'm not familiar with ARM development, but I'd accept a contribution if someone's able to set up the ARM build.

**Comment by br0tda** [comment]
I need that build to, cause compiling following the instruction gives me everytime errors. Please! Consider to include that build

**Comment by br0tda** [comment]
Hi, check my repo [here](https://github.com/br0tda/tdlib_raspberry)! You can find a pre-built version of tdlib for Raspberry Pi and also a guide to build by your own!
