### ISSUE TITLE
version 1.6.9 needed

### ISSUE THREAD

**Issue by mccoysc** [ForNeVeR/tdlib.native#33]
as the title

**Comment by mccoysc** [comment]
@ForNeVeR what time for version 1.6.9?

**Comment by ForNeVeR** [comment]
I am sorry, but it's impossible. td maintainers refuse to add any release tags for their patch releases, so I couldn't know from which commit I'm supposed to build the release. So, for now, I cannot support any patch releases (e.g. `1.6.x`), and could only support `1.6.0` and `1.7.0`.

The maintainers have been asked about that twice: https://github.com/tdlib/td/issues/913, https://github.com/tdlib/td/issues/1052, and refused to add the corresponding tags.
