### ISSUE TITLE
Update to 1.7

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/tdlib.native#34]
Now, when tdsharp is readying 1.7 release, we'll need to update ASAP.

**Comment by DenomikoN** [comment]
So, is there any problems?

**Comment by ForNeVeR** [comment]
Yes. I have no spare time for this. Wanna help?

**Comment by P9os** [comment]
> Yes. I have no spare time for this. Wanna help?

Are you need new compiled binaries?

**Comment by DenomikoN** [comment]
I've managed to compile for .NET myself, ok to donate.

**Comment by ForNeVeR** [comment]
> Are you need new compiled binaries?

I don't need, and won't publish any binaries received from strangers. Here, I purposefully only compile from sources on CI, openly, for everyone to verify (to avoid any possibility of fraud).

What I need is a PR in this repository which will update tdlib to 1.7, and will pass the integration tests.

**Comment by ForNeVeR** [comment]
The new package release is brewing right now.
