### ISSUE TITLE
how to remove ', TDLib 1.6.0' from aplication_version value in Telegram session

### ISSUE THREAD

**Issue by alirayaneh** [ForNeVeR/tdlib.native#37]
hi
when we create session by tdlib that add extra string to application_version value in telegram session
this is my parameter value
tdlibParameters: {
device_model: 'Firefox',
system_version: 'Windows',
application_version: '5.7.0',
enable_storage_optimizer: true,
apiId: api_id,
apiHash: api_hash
}
but when i see telegram sessions

application_version: 5.7.0, TDLib 1.6.0

how to caler this copy right

**Comment by ForNeVeR** [comment]
I can see that you've [reported that upstream](https://github.com/tdlib/td/issues/1470) (which was the right decision). Thus closing.

**Comment by alirayaneh** [comment]
thanks
