### ISSUE TITLE
Update to 1.7.9 for Nuget

### ISSUE THREAD

**Issue by Shpakoff** [ForNeVeR/tdlib.native#48]

**Comment by Shpakoff** [comment]
I am using version 1.7.0 TDLib.Native from Nuget and awaiting update to 1.7.9 . Will there be a version update in Nuget today?

**Comment by ForNeVeR** [comment]
> Will there be a version update in Nuget today?

Possibly.

**Comment by ForNeVeR** [comment]
[tdlib.native v1.7.9](https://www.nuget.org/packages/tdlib.native/1.7.9) has been published!
