### ISSUE TITLE
Appveyor and GitHub Actions create different kinds of releases

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/tdlib.native#49]
While preparing v1.7.9, I've noticed that GHA create a draft release, and Appveyor creates a real one:
<img width="874" alt="image" src="https://user-images.githubusercontent.com/92793/144717345-b2a1e0be-d500-4a14-a344-496bb1b8f6a6.png">

This lead to an issue because Appveyor wasn't able to upload the second build (it seen two releases with the same name).

**Comment by jlcvp** [comment]
You need to set draft to ` false` in `main.yml` https://github.com/ForNeVeR/tdlib.native/blob/65870d69e006b106ef3a6495b13baa03fd0b5389/.github/workflows/main.yml#L214
