### ISSUE TITLE
 Failed to sync binlog

### ISSUE THREAD

**Issue by farhad-rad** [ForNeVeR/tdlib.native#53]
Running some methods of TdSharp results in below error which is related to tdlib.native.
Here is the info in the debug console after calling ```TdLib.TdClient.CheckDatabaseEncryptionKeyAsync```:
```
[Client.cpp:278][&td_requests]   Begin to wait for updates with timeout 0.100000
[Td.cpp:3072][#1][!Td][&td_requests]     Receive request 3: checkDatabaseEncryptionKey {
  encryption_key = bytes [0] { }
}
[Binlog.cpp:419][#1][!Td][&status.is_error()]    Failed to sync binlog: [WindowsError : Insufficient system resources exist to complete the requested service. : 1450 : Sync failed]
(process 5840) application exited with code -1073740791.
```
I'm using ```Tdlib v1.7.9``` and ```TdLib.Native 1.7.9``` on x64 windows 11 Pro. The project is built over .Net 5 for web (Actual target OS is windows server 2019)
I double checked system resources. There was only 15% CPU usage and almost 3 Gb of RAM.
I also disabled anti-virus (i found out it might be the cause) with no luck!
It there something im missing?

**Comment by ForNeVeR** [comment]
Looks like a TDLib issue, and not of tdlib.native. Please [report upstream](https://github.com/tdlib/td).
