### ISSUE TITLE
libssl3: Ubuntu 22.04 version please

### ISSUE THREAD

**Issue by mortezae** [ForNeVeR/tdlib.native#66]
Ubuntu has switched to libssl3. I personally compiled tdlib but encountered runtime error when running the binary:
  `Error while reading RSA public key.`
Could you compile it please?

**Comment by mortezae** [comment]
Turned out that you can install libssl1 from [older](https://launchpad.net/ubuntu/+source/openssl/1.1.1l-1ubuntu1.3) versions of Ubuntu. I don't know if it's ok, btw it just works.

**Comment by ForNeVeR** [comment]
Ow, that's painful.

How do you use the package? Using .NET or something else, like Node.js?

I am asking because for .NET I'll have to figure out how to pack different Linux artifacts into the same package. I _think_ that should be possible, but I've never done that, yet.

**Comment by mortezae** [comment]
That's kinda upstream and I should ask about it in tdlib/td/issues. Anyway for now we can use old ssl package, and let's wait for tdlib's next release.
And I'm personally using Node.js.
Thanks.

**Comment by ForNeVeR** [comment]
I think I'm ready to start working on libssl3 binaries (ubuntu 22.04-based), provided that tdlib itself is compatible with that version.

**Comment by sanderwollaert** [comment]
I have the same issue.

I made a temporary fix.
I'm made a fork of the code. 
Changed the build agents to ubuntu-22.04 and referenced the output files directly.

I now have a working .net 8 application hosted on a linux azure app service.

Hoping for an official release
