### ISSUE TITLE
Updates to the current version of tdLib 1.8.9?

### ISSUE THREAD

**Issue by nikolaykusch** [ForNeVeR/tdlib.native#77]
Current version tdlib.native return some messages as messageUnsupported.

**Comment by ForNeVeR** [comment]
> any commit from the last days

The last days of my sanity, no less.

**Comment by ForNeVeR** [comment]
Anyway, you're right, and we should try to prepare a fresh release.

**Comment by nikolaykusch** [comment]
Thank you!

**Comment by ForNeVeR** [comment]
The package has been published. But it is currently unlisted (while I'm working on tdsharp).
