### ISSUE TITLE
No generation of .dlls when using NuGet package in C#

### ISSUE THREAD

**Issue by lnx1-1** [ForNeVeR/tdlib.native#81]
Hey People :) first, a big thank you for your work on tdlib! I realy appreciate ist.

To the bug Itself:

When I build my project in which I installed the `TDLib 1.8.9.1` and `tdlib.native 1.8.9` __the DLL are all missing in the output folder.__

`tdjson.dll` `zlib1.dll` `libssl-3-x64.dll` `libcrypto-3-x64.dll`

If I copy the prebuild ones to the bin folder, everything works fine. But as far as I understood the purpose behind the `tdlib.native` is to provide prebuild dlls to be copied to the binary folder during build, right?

<details>
<summary>Setup informations</summary>

I'm using Jetbrains Rider with multiple Class Library Projects.

Machine:
Windows 10 - 64bit

### Here is my Build Config:
![grafik](https://user-images.githubusercontent.com/59773698/219869960-b94fe914-3c4f-4a52-b451-a8125a2b4805.png)

### csproj
~~~
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>9</LangVersion>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Configurations>Debug;Release;Debug x64</Configurations>
        <Platforms>AnyCPU;x64</Platforms>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug x64|x64' ">
      <DebugSymbols Condition=" '$(DebugSymbols)' == '' ">true</DebugSymbols>
      <Optimize Condition=" '$(Optimize)' == '' ">false</Optimize>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="NLog" Version="5.1.1" />
      <PackageReference Include="TDLib" Version="1.8.9.1" />
      <PackageReference Include="tdlib.native" Version="1.8.9" />
      <PackageReference Include="xunit" Version="2.4.2" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="ApplicationLayer" />
    </ItemGroup>    

    <ItemGroup>
      <None Update="NLog.config">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>    

    <ItemGroup>
      <ProjectReference Include="..\..\..\..\...\ProjectCommons\ProjectCommons.csproj" />
    </ItemGroup>

</Project>
~~~

## Assembly View

![grafik](https://user-images.githubusercontent.com/59773698/219870286-e39f3279-d999-4965-881d-028c257e1367.png)

</details>

**Comment by ForNeVeR** [comment]
> But as far as I understood the purpose behind the `tdlib.native` is to provide prebuild dlls to be copied to the binary folder during build, right?

Not that simple.

tdlib.native provides native libraries in a way they'll be picked up by the .NET runtime loader, among other things. This doesn't technically require them to be _copied on build_.

In this case, you have a .NET Standard library that is not directly runnable; that's why no binraies is even possible to copy to its output: there are no compatible runtimes defined in it.

Try doing the same with a .NET _executable_ (not a library!), and you'll see the difference in the output behavior.

I think that if you create an executable (on .NET 6 or 7, for example) depending on your .NET Standard project, then the binaries will be properly copied on build (or, better, on `dotnet publish`).

**Comment by lnx1-1** [comment]
Okay, I understand :)
I was wondering because I have a second NuGet package [OpenTAP](https://github.com/opentap/opentap/tree/main/nuget) 
where exactly this is happening. I'm building a class library for Netstandard and all files are copied by the plugin on Build.

But i see that this isn't the way this package is meant to work. So I will just let it copy another way automaticly. 

__Thank you for the quick answer and explanation!!__

**Comment by ForNeVeR** [comment]
OpenTAP works in another way (with custom `.nuspec` and different file layout), so I guess they have different goals.
