### ISSUE TITLE
 Error when creating a client, when moving from net 7.0 to net 8.0, on docker

### ISSUE THREAD

**Issue by VadimAND** [ForNeVeR/tdlib.native#95]
There was a problem when changing the version from .NET 7 to .NET 8

The error only appears when using Docker. The build file remains the same.

The error appears when creating a client:
_client = new TdClient();
![image](https://github.com/ForNeVeR/tdlib.native/assets/39476457/9385e78a-9445-4cee-a4c5-18334ab27669)

Package versions
TDLib (1.8.21)
TDLib.Api (1.8.21)
tdlib.native(1.8.21)

libraries in the runtimes/linux-x64/native folder:
libtdactor.a
libtdapi.a
libtdclient.a
libtdcore.a
libtddb.a
libtdjson.so
libtdjson.so.1.8.21
libtdjson_private.a
libtdjson_static.a
libtdnet.a
libtdsqlite.a
libtdutils.a
7.0 ![image](https://github.com/ForNeVeR/tdlib.native/assets/39476457/f6134fc6-f5af-496d-83f9-9e9b5a65ed7a)
8.0 ![image](https://github.com/ForNeVeR/tdlib.native/assets/39476457/33eb0613-8cf8-41aa-8c5d-4f3daf726c14)

The error itself:
Unable to load shared library 'tdjson' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable:
/app/bin/Debug/net8.0/runtimes/linux-x64/native/tdjson.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.4/tdjson.so: cannot open shared object file: No such file or directory
/app/bin/Debug/net8.0/tdjson.so: cannot open shared object file: No such file or directory
libssl.so.1.1: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.4/libtdjson.so: cannot open shared object file: No such file or directory
/app/bin/Debug/net8.0/libtdjson.so: cannot open shared object file: No such file or directory
/app/bin/Debug/net8.0/runtimes/linux-x64/native/tdjson: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.4/tdjson: cannot open shared object file: No such file or directory
/app/bin/Debug/net8.0/tdjson: cannot open shared object file: No such file or directory
/app/bin/Debug/net8.0/runtimes/linux-x64/native/libtdjson: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.4/libtdjson: cannot open shared object file: No such file or directory
/app/bin/Debug/net8.0/libtdjson: cannot open shared object file: No such file or directory

**Comment by ForNeVeR** [comment]
> libssl.so.1.1: cannot open shared object file: No such file or directory

Do you have `libssl.so.1.1` on that computer?

**Comment by sanderwollaert** [comment]
I have the same issue.

I made a temporary fix.
I'm made a fork of the code.
Changed the build agents to ubuntu-22.04 and referenced the output files directly.

I now have a working .net 8 application hosted on a linux azure app service.

Hoping for an official release
